### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by VedangW** [tkipf/gae#12]
Hi, I have an issue similar to one in 'gcn' (https://github.com/tkipf/gcn/issues/6).

On running the ```train.py``` file the following error is observed:

```bash
vedang@vedang-HP-Pavilion-Notebook:~/gae/gae$ python train.py --dataset cora
Traceback (most recent call last):
  File "train.py", line 40, in <module>
    adj, features = load_data(dataset_str)
  File "/home/vedang/anaconda3/lib/python3.6/site-packages/gae-0.0.1-py3.6.egg/gae/input_data.py", line 19, in load_data
    objects.append(pkl.load("data/ind.{}.{}".format(dataset, names[i])))
  File "/home/vedang/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```
I changed the read format to ```open(filename, 'rb')``` but now I get the following error:

```bash
vedang@vedang-HP-Pavilion-Notebook:~/gae/gae$ python train.py --dataset cora
Traceback (most recent call last):
  File "train.py", line 40, in <module>
    adj, features = load_data(dataset_str)
  File "/home/vedang/anaconda3/lib/python3.6/site-packages/gae-0.0.1-py3.6.egg/gae/input_data.py", line 19, in load_data
    objects.append(pkl.load("data/ind.{}.{}".format(dataset, names[i], 'rb'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x87 in position 32: ordinal not in range(128)
```
Can you please let me know what changes can be done or look into this issue?

**Comment by tkipf** [comment]
Can you try running this in Python 2.7?

**Comment by VedangW** [comment]
It's working in python 2.7. Thanks a lot!
