### ISSUE TITLE
InvalidArgumentError for large dataset

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [tkipf/gae#27]
Hi Tomas,

I am able to use gae on the small dataset(<10k nodes) without any problem but when I tried on large dataset. I am having the following error:

2019-03-15 15:36:48.653709: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
 File "train.py", line 187, in <module>
   outs = sess.run([opt.opt_op, opt.cost, opt.accuracy], feed_dict=feed_dict)
 File "/home/gurukar.1/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
   run_metadata_ptr)
 File "/home/gurukar.1/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
   feed_dict_tensor, options, run_metadata)
 File "/home/gurukar.1/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
   run_metadata)
 File "/home/gurukar.1/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
   raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape output type is 32-bit  but dim 0 is 3187957444
     [[node optimizer/gradients/optimizer/logistic_loss/mul_1_grad/Shape_1 (defined at /scratch/line_verse/vag/vgae/gae/optimizer.py:15)  = Shape[T=DT_FLOAT, out_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gcnmodelae/innerproductdecoder_1/Reshape)]]

I did some research (https://github.com/tensorflow/tensorflow/issues/23107) and it seems that it relates to int32 datatype. I am thinking about change all int32 in optimizer.py from int32 to int64. Do u think it will work? I would like to consult you at first since it takes the quite long time to run on the large dataset.

**Comment by ChanakaCooray** [comment]
@Chen-Cai-OSU Were you be able to solve this issue?
