### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by yjyGo** [tkipf/gae#37]
I use my own data, a 8424 X 8424 adjacent matrix, a 8424 X 768 feature matrix. When I ran the model, the following error occurred:
Traceback (most recent call last):
  File "/home/yangjingying/PycharmProjects/gae-master/gae/train.py", line 53, in <module>
    adj_train, train_edges, val_edges, val_edges_false, test_edges, test_edges_false = mask_test_edges(adj)
  File "/home/yangjingying/PycharmProjects/gae-master/gae/preprocessing.py", line 101, in mask_test_edges
    assert ~ismember(test_edges_false, edges_all)
  File "/home/yangjingying/PycharmProjects/gae-master/gae/preprocessing.py", line 62, in ismember
    rows_close = np.all(np.round(a - b[:, None], tol) == 0, axis=-1)
MemoryError

**Comment by kbvstmd** [comment]
Have you solve this issue?@yiyGo,if so how to deal with it ,thanks!
