### ISSUE TITLE
Problems I encountered in the train.py program

### ISSUE THREAD

**Issue by 6ADAM6** [tkipf/gae#82]
Hello! @tkipf 
First of all, I appreciate and admire the amazing job you've done!!
But I'm having some problems running train.py, I don't know if it is a problem with the version of the scipy, The program error shows that the rank of the array is not 2, The specific error information is as follows: 
Traceback (most recent call last):
  File "D:\Python\Python_PyCharm\gae-master(1)\gae-master\gae\train.py", line 44, in <module>
    adj_orig = adj_orig - sp.dia_matrix((adj_orig.diagonal()[np.newaxis, :], [0]), shape=adj_orig.shape)
  File "E:\Anaconda3\envs\tensorflow-1.10.0\lib\site-packages\scipy\sparse\dia.py", line 138, in __init__
    raise ValueError('data array must have rank 2')
ValueError: data array must have rank 2

Sorry to delay your time, I hope you can enlighten me! Thank you!!

**Comment by 6ADAM6** [comment]
@tkipf

**Comment by 6ADAM6** [comment]
@tkipf @shoniko @gokceneraslan @philipjackson 
I know what the problem is, In NumPy, the.diagonal() function usually takes a one-dimensional array, but when my code runs it takes a two-dimensional array, which results in a three-dimensional array after adding one dimension, which does not meet the requirements of the sp.dia_matrix () function. 
Although I have found the problem, I have not yet found a solution. I hope you can give me your advice. Thank you very much!
